### ISSUE TITLE
Investigate if current implementation will work on Android Q as-is.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-campaigns-android#15]
We cannot yet target the Android Q SDK.  Only once it has been out for one whole version cycle can we do so (and it's still in beta for now).

The most relevant Q change is with location services, particularly with getting location updates in background and therefore enabling geofences, beacons, and location-segmented campaigns.

However, in the meantime we must support the following cases:

a) App not targeting Q is running on Q.  Does Rover work as expected, particularly location updates;
b) App targeting Q is running on Q. Necessary compatibility modes that make a) case work may fail on b).

**Comment by samwoodall** [comment]
Already a very similar issues that i'll add some of the description here to
