### ISSUE TITLE
Always store Notifications in the NotificationsRepository, even if they don't have isNotificationCenterEnabled turned on.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-campaigns-android#40]
* Look in NotificationDispatcher.kt, Line ~123.
* Then we should smoke test a bit afterwards to be sure that notifications without isNotificationCenterEnabled don't show up in the Notification Center or similar.

Then we should release it as v3.0.1, as a hotfix.

**Comment by samwoodall** [comment]
Fixed in v3.1.1
