### ISSUE TITLE
Prevent unhandled exceptions in location module from crashing app.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-campaigns-android#46]
This is apparently happening with denied background location permission on Android Q.  See about reproducing this with an Android Q device.

Note that is ticket is *not* exhaustive Android Q target API support.  This is about solving an existing error handling bug that happens to be triggered by running on Q.

**Comment by samwoodall** [comment]
Closing due to this issue being resolved in Q beta 4
